# Generated by Django 6.0.6 on 2026-07-03 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('max_people', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('package_type', models.CharField(choices=[('Family', 'Family'), ('Honeymoon', 'Honeymoon'), ('Adventure', 'Adventure'), ('Solo', 'Solo'), ('Corporate', 'Corporate')], max_length=20)),
                ('image', models.ImageField(upload_to='packages/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='destinations.destination')),
            ],
        ),
    ]
