# Generated by Django 6.0.6 on 2026-07-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('Beach', 'Beach'), ('Hill', 'Hill'), ('Adventure', 'Adventure'), ('Religious', 'Religious'), ('Wildlife', 'Wildlife'), ('Heritage', 'Heritage')], default='Heritage', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
    ]
